config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'items#index'

  resources :discounts

  resources :items do
    collection do
      get ':id/add_to_basket' => 'items#add_to_basket'
    end
  end

  get 'my_basket' => 'baskets#show'
  get 'reset' => 'baskets#reset'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
# frozen_string_literal: true

class Basket < ApplicationRecord
  has_many :basket_items, dependent: :delete_all
  has_many :items, through: :basket_items

  attribute :price, :float, default: 0.0
  attribute :final_price, :float, default: 0.0
end

app/models/basket_item.rb
# frozen_string_literal: true

class BasketItem < ApplicationRecord
  belongs_to :item
  belongs_to :basket

  attribute :price, :float, default: 0.0
  attribute :final_price, :float, default: 0.0
end

app/models/discount.rb
# frozen_string_literal: true

class Discount < ApplicationRecord
  has_many :items
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :name, :code, :price, presence: true

  has_many :basket_items, dependent: :delete_all
  has_many :baskets, through: :basket_items
  belongs_to :discount
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/baskets_controller.rb
# frozen_string_literal: true

class BasketsController < ApplicationController
  before_action :set_basket, only: %i[show reset]

  def show
    @basket_items = @basket.basket_items.order(updated_at: :asc)
  end

  def reset
    @basket.update(price: 0, final_price: 0)
    BasketItem.delete_all
    respond_to do |format|
      format.html { redirect_to my_basket_path, notice: 'Reset is done!' }
    end
  end

  private

  def set_basket
    @basket = Basket.first
  end
end

app/controllers/discounts_controller.rb
# frozen_string_literal: true

class DiscountsController < ApplicationController
  before_action :set_discount, only: %i[show edit update destroy]

  # GET /discounts or /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1 or /discounts/1.json
  def show; end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit; end

  # POST /discounts or /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to discount_url(@discount), notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1 or /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to discount_url(@discount), notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1 or /discounts/1.json
  def destroy
    @discount.destroy

    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_discount
    @discount = Discount.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def discount_params
    params.require(:discount).permit(:name, :description)
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy add_to_basket]
  before_action :set_basket, only: %i[add_to_basket]

  def add_to_basket
    if Items::AddToBasketService.new(@item, @basket).call
      if Baskets::UpdatePriceService.new(@basket).call
        respond_to do |format|
          format.html { redirect_to my_basket_path, notice: 'Item was successfully added to the basket.' }
        end
      end
    end
  end

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_basket
    @basket = Basket.first
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :code, :price, :discount_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/discounts_helper.rb
# frozen_string_literal: true

module DiscountsHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/baskets/show.html.erb
<div class="container">
  <div class="row align-items-start">
    <table class="table">
      <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Code</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">To Pay (with discount)</th>
      </tr>
      </thead>
      <tbody>
        <% @basket_items.each do |basket_item| %>
          <tr>
            <td><img src="<%= basket_item.item.photo %>" class="card-img-top" alt="..." style="height: 50px; width: 50px;"></td>
            <td><%= basket_item.item.code %></td>
            <td><%= basket_item.item.name %></td>
            <td><%= basket_item.quantity %></td>
            <td><%= basket_item.price %></td>
            <td><%= basket_item.final_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <table>
      <tr>
        <td><h5>Price:</h5></td>
        <td><h5><%= @basket.price %></h5></td>
      </tr>
      <tr>
        <td><h5>To Pay (with discount):</h5></td>
        <td><h5><%= @basket.final_price %></h5></td>
      </tr>
    </table>
    <div>
      <br>
      <%= link_to 'Continue Shopping', root_path %>
      <br>
      <%= link_to 'Reset Basket', reset_path %>
    </div>
  </div>
</div>

app/views/discounts/_form.html.erb
<%= form_with(model: discount, local: true) do |form| %>
  <% if discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= discount.name %></td>
        <td><%= discount.description %></td>
        <td><%= link_to 'Show', discount %></td>
        <td><%= link_to 'Edit', edit_discount_path(discount) %></td>
        <td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount', new_discount_path %>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Back', discounts_path %>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @discount.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @discount.description %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, {class: "form-label" } %>
    <%= form.text_field :name, {class: "form-control"} %>
  </div>

  <div class="field">
    <%= form.label :code, {class: "form-label" } %>
    <%= form.text_field :code, {class: "form-control"} %>
  </div>

  <div class="field">
    <%= form.label :price, {class: "form-label" } %>
    <%= form.number_field :price, {class: "form-control"} %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.select :discount_id, Discount.all.pluck(:name,:id),{prompt:'select'},{class: "form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <div class="row align-items-start">
    <div class="col-4">
      <h1>Editing Item</h1>

      <%= render 'form', item: @item %>
    </div>
  </div>
  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="row align-items-start">
    <p id="notice"><%= notice %></p>

    <h1>Products</h1>

    <% @items.each do |item| %>
      <div class="card" style="width: 18rem;">
        <img src="<%= item.photo %>" class="card-img-top" alt="..." style="height: 250px;">
        <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
          <p class="card-text"><%= item.code %></p>
          <h5 class="card-title"><%= item.price %>$</h5>
          <a href="<%= "items/#{item.id}/add_to_basket" %>" class="btn btn-dark">Add to Basket</a>
        </div>
      </div>
    <% end %>
    <div>
      <br>
      <%= link_to 'View Basket', my_basket_path %>
      <br>
      <%= link_to 'New Item', new_item_path %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @item.code %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @item.discount.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebasket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>